# Site settings
title: Southampton Sailing Robot Team
email: sotonsailrobot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

blog_url: https://blog.sotonsailrobot.org
github_url: https://github.com/Maritime-Robotics-Student-Society/sailing-robot.git
twitter_username: SotonSailRobot
github_username: Maritime-Robotics-Student-Society

# Build settings
markdown: kramdown

supporters: 
